---

#Note that I don't call update_cache=true for all of these
#You can do that in a playbook before this one if you want

- name: update apt cache (if out of date)
  #Updates it only every 4 hours
  apt: update_cache=yes cache_valid_time={{ 60*60*4 }}
  sudo: true

# Needed for add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=latest
  tags:
    - apt

- name: Add repository key
  apt_key: id=ACCC4CF8 url='https://www.postgresql.org/media/keys/ACCC4CF8.asc' state=present
  tags:
    - apt

- name: Add PostgreSQL repository
  apt_repository: repo='{{ postgresql.repo }}' state=present
  register: added_postgres_repo
  tags:
    - apt

- name: Update apt cache if we just installed the Postgres repo
  apt: update_cache=yes
  sudo: true
  when: added_postgres_repo.changed
  tags:
    - apt


